name: MC-Runtime-Test
description: Runs the MC client inside your CI
author: 3arthqu4ke
branding:
  icon: play
  color: green

inputs:
  mc:
    description: Minecraft version to run
    required: true
    default: "1.20.4"
  modloader:
    description: Modloader to install (forge, neoforge, fabric)
    required: true
    default: "fabric"
  regex:
    description: Regex to match the modloader jar
    required: true
    default: ".*fabric.*"
  java:
    description: Java version to use
    required: true
    default: "17"
  dummy-assets:
    description: Use dummy assets during testing
    required: true
    default: "true"
  mc-runtime-test:
    description: MC-Runtime-Test jar to download (none, lexforge, neoforge, fabric)
    required: true
    default: "fabric"
  xvfb:
    description: Runs the game with Xvfb (if false, add the -lwjgl argument)
    required: false
    default: "true"
  headlessmc-command:
    description: Command-line arguments for HeadlessMC
    required: false
    default: "--jvm -Djava.awt.headless=true"
  fabric-api:
    description: Fabric API version to download (e.g. 0.97.0) or none
    required: false
    default: "none"
  fabric-gametest-api:
    description: Fabric GameTest API version (e.g. 1.3.5+85d85a934f) or none
    required: false
    default: "none"
  download-hmc:
    description: Download HeadlessMC (if false, add a headlessmc-launcher.jar to the cwd)
    required: false
    default: "true"
  hmc-version:
    description: HeadlessMC version to download
    required: false
    default: "2.4.1"

runs:
  using: composite
  steps:
    - name: Bootstrap HeadlessMC
      run: |
        mkdir -p HeadlessMC run/mods
        cat <<EOF >> HeadlessMC/config.properties
        hmc.java.versions=$JAVA_HOME/bin/java
        hmc.gamedir=$PWD/run
        hmc.offline=true
        hmc.rethrow.launch.exceptions=true
        hmc.exit.on.failed.command=true
        EOF
      shell: bash

    - if: inputs.dummy-assets == 'true'
      name: Configure Dummy Assets
      run: echo hmc.assets.dummy=true >> HeadlessMC/config.properties
      shell: bash

    - if: inputs.download-hmc == 'true'
      name: Get HeadlessMC
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 3arthqu4ke/headlessmc
        tag: ${{ inputs.hmc-version }}
        fileName: headlessmc-launcher-${{ inputs.hmc-version }}.jar

    - name: Download ${{ inputs.mc }}
      run: java -jar headlessmc-launcher.jar --command download ${{ inputs.mc }}
      shell: bash

    - name: Download ${{ inputs.modloader }}
      run: java -jar headlessmc-launcher.jar --command ${{ inputs.modloader }} ${{ inputs.mc }} --java ${{ inputs.java }}
      shell: bash

    - if: inputs.mc-runtime-test != 'none'
      name: Get mc-runtime-test
      uses: robinraju/release-downloader@v1.11
      with:
        repository: 3arthqu4ke/mc-runtime-test
        tag: "2.4.2"
        fileName: mc-runtime-test-${{ inputs.mc }}-2.4.2-${{ inputs.mc-runtime-test }}-release.jar
        out-file-path: run/mods

    - if: inputs.fabric-api != 'none'
      name: Download fabric-api v${{ inputs.fabric-api }}
      run: >
        mvn dependency:get 
        -Dartifact=net.fabricmc.fabric-api:fabric-api:${{ inputs.fabric-api }}+${{ inputs.mc }}
        -Ddest=run/mods/fabric-api-${{ inputs.fabric-api }}+${{ inputs.mc }}.jar
        -DrepoUrl=https://maven.fabricmc.net/
      shell: bash

    - if: inputs.fabric-gametest-api != 'none'
      name: Download fabric-gametest-api v${{ inputs.fabric-gametest-api }}
      run: >
        mvn dependency:get 
        -Dartifact=net.fabricmc.fabric-api:fabric-gametest-api-v1:${{ inputs.fabric-gametest-api }}
        -Ddest=run/mods/fabric-gametest-api-v1-${{ inputs.fabric-gametest-api }}.jar
        -DrepoUrl=https://maven.fabricmc.net/
      shell: bash

    - name: Configure game
      run: |
        cat <<EOF >> run/options.txt
        onboardAccessibility:false
        pauseOnLostFocus:false
        EOF
      shell: bash

    - if: inputs.xvfb == 'true'
      name: Run game with xvfb
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y x11-xserver-utils
        xvfb-run java -Dhmc.check.xvfb=true -jar headlessmc-launcher.jar --command launch ${{ inputs.regex }} -regex ${{ inputs.headlessmc-command }}
      shell: bash

    - if: inputs.xvfb != 'true'
      name: Run game
      run: java -jar headlessmc-launcher.jar --command launch ${{ inputs.regex }} -regex ${{ inputs.headlessmc-command }}
      shell: bash
