---
name: Build specific version reusable

"on":
  workflow_call:
    inputs:
      dir:
        description: The directory to build in
        required: true
      mc:
        description: The MC version to build
        required: true
      lex:
        description: The LexForge version to use
        required: true
      neo:
        description: The NeoForge version to use
        required: true
      java:
        description: The Java version to use
        required: true
      upload:
        description: Upload the build artifacts
        default: true
        type: boolean

jobs:
  build:
    name: Build ${{ inputs.dir }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - namee: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java }}
          distribution: adopt

      - name: Gradle build
        working-directory: ./${{ inputs.dir }}
        run: >
          ./gradlew build --stacktrace
          -Pminecraft_version=${{ inputs.mc }}
          -Plexforge_version=${{ inputs.lex }}
          -Pneoforge_version=${{ inputs.neo }}

      - name: Upload artifacts
        if: inputs.upload
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ inputs.dir }}
          path: ./${{ inputs.dir }}/build/libs/*.jar
