---
name: Build specific version reusable

"on":
  # pull_request: # TODO: build relevant jobs with paths-filter

  release:
    types: [created]

  workflow_call:
    inputs:
      dir:
        description: The directory to build in
        required: true
        type: string
      mc:
        description: The MC version to build
        required: true
        type: string
      lex:
        description: The LexForge version to use
        required: true
        type: string
      neo:
        description: The NeoForge version to use
        required: true
        type: string
      java:
        description: The Java version to use
        required: true
        type: string
      upload:
        description: Upload the build artifacts
        default: true
        type: boolean

env:
  dir: ${{ inputs.dir || 'api' }}
  mc: ${{ inputs.mc || 'api' }}
  java: ${{ inputs.java || '8' }}

jobs:
  build:
    name: Build ${{ env.mc }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            api
            ${{ env.dir }}

      - name: Cache build
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.dir }}/build
          key: build-${{ hashFiles(format('{0}/[a-z]**', env.dir), 'api/**') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.java }}

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - if: |
          steps.cache.outputs.cache-hit != 'true'
          && github.event_name != 'release'
        name: Gradle build
        run: >
          CI=true ./gradlew build --stacktrace
          -Pminecraft_version=${{ inputs.mc }}
          -Plexforge_version=${{ inputs.lex }}
          -Pneoforge_version=${{ inputs.neo }}
        working-directory: ${{ env.dir }}

      - if: github.event_name == 'release'
        name: Gradle publish
        env:
          IS_MAVEN_PUB: true
          DEPLOY_TO_GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: CI=true ./gradlew publish
        working-directory: ${{ env.dir }}

      - name: Upload artifacts
        if: |
          inputs.upload
          && github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ env.mc }}
          path: ${{ env.dir }}/build/libs/*.jar
