---
name: Release API

"on":
  # pull_request: # TODO: build relevant jobs with paths-filter

  release:
    types: [created]

jobs:
  release:
    name: Release
    uses: ./.github/workflows/build-specific-reusable.yml
    with:
      dir: api
      java: 8
      publish: true
      upload: false
