---
name: Run latest gametests

"on":
  workflow_dispatch:

jobs:
  build-gametest:
    name: Build GameTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java [adopt-17] # TODO: update Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Gradle build
        working-directory: ./gametest
        run: ./gradlew build --stacktrace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gametest-jars
          path: ./gametest/build/libs/*.jar

  build-latest: # FIXME: replace with reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Build latest
        working-directory: ./1_20
        run: ./gradlew build --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: latest-jars
          path: ./1_20/build/libs/*.jar

  run:
    needs: [build-gametest, build-latest]
    strategy:
      matrix:
        version: # FIXME: not used
          - { dir: 1_20, mc: 1.20.6, type: lexforge, modloader: forge, regex: .*forge.*, java: 21 }
          - { dir: 1_20, mc: 1.20.6, type: neoforge, modloader: neoforge, regex: .*neoforge.*, java: 21 }
          - { dir: 1_20, mc: 1.20.6, type: fabric, modloader: fabric, regex: .*fabric.*, java: 21 }
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Copy mod files # TODO: avoid this step by downloading directly to run/mods
        run: |
          mkdir -p run/mods
          cp gametest-jars/clientgametest-*.jar run/mods
          cp latest-jars/mc-runtime-test-*-release.jar run/mods

      - name: Run game for version
        id: local-action
        uses: ./
        with:
          mc-runtime-test: none
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1"
          fabric-api: 0.97.0
          fabric-gametest-api: 1.3.5+85d85a934f
          checkout: false
