---
name: Test the local action

"on":
  push:

env:
  JAVA_VERSION: 21

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
      - name: Local Action Call
        id: local-action
        uses: ./
        with:
          mc: 1.20.4
          modloader: fabric
          regex: .*fabric.*
          mc-runtime-test: fabric
          java: ${{ env.JAVA_VERSION }}
          fabric-api: 0.97.0
          fabric-gametest-api: 1.3.5+85d85a934f
